### ISSUE TITLE
Escape ".__" in code samples of docs

### ISSUE THREAD

**Issue by ChillarAnand** [frappe/frappe_docs#148]
Frappe is raising invalid template exception where there is [`.__` in a template](https://github.com/frappe/frappe/blob/develop/frappe/utils/jinja.py#L79). Not sure why this is added. May to prevent from calling private python methods?

Because of this, [qunit-testing](https://frappeframework.com/docs/user/en/guides/automated-testing/qunit-testing) page is broken.

**Comment by gavindsouza** [comment]
Possible fix: https://github.com/frappe/frappe/pull/13842
