### ISSUE TITLE
Unable to install working version of frappe_docs

### ISSUE THREAD

**Issue by gwhitney** [frappe/frappe_docs#16]
I am interested in contributing a section to the Frappe Framework docs on using the DocFields of a DocType to tailor the Form view: how to break it into sections, how to make the sections collapsible, what column breaks do, how to set up the grid view of a child table, what the columns field means/does, that sort of thing, as I found it initially somewhat confusing, there are many questions about columns in the discussion forum, and I don't see this type of information in the Frappe Framework docs.

So naturally, as with contributing to the ERPNext Documentation, per the page https://github.com/frappe/erpnext/wiki/How-To-Contribute-to-the-ERPNext-Documentation-(The-Lengthy-Version) , I wanted to install a working clone of the Frappe Framework documentation. So I created a new bench, and then in that bench I executed:

```
bench new-site mysub.mydomain.tld
bench get-app frappe_docs
bench get-app frappe_theme
bench --site mysub.mydomain.tld install frappe_docs
bench --site mysub.mydomain.tld install frappe_theme![Screenshot_2020-07-28_09-17-37](https://user-images.githubusercontent.com/3825429/88692676-34190600-d0b3-11ea-8936-734930ff767c.png)

bench start
```

But now when I navigate to http://mysub.mydoman.tld:8001 (not :8000 as there is a totally separate bench on the same machine already using :8000), I get a "Not Found" page pictured in the screen shot below, and the "Back to Home" button simply reproduces the same "Not Found" page.

How can I get my clone of frappe_docs working? I will be happy to put updated installation instructions into the README.md file in my PR as well, if I can get this working. Thank you for your help/advice.

![Screenshot_2020-07-28_09-17-37](https://user-images.githubusercontent.com/3825429/88692676-34190600-d0b3-11ea-8936-734930ff767c.png)

**Comment by gavindsouza** [comment]
@gwhitney does http://mysub.mydoman.tld:8001//docs not show you the docs page?

**Comment by gwhitney** [comment]
Why, in fact it does :-)

It never occurred to me that there would be no home page on a working installation and I didn't know the /docs URL.

Would you like me to submit a pull request for the Readme page to include my little bit of installation information above and mention that once running it will serve /docs but doesn't provide a home page? 

Thanks! Glen

**Comment by gavindsouza** [comment]
> Would you like me to submit a pull request for the Readme page to include my little bit of installation information above and mention that once running it will serve /docs but doesn't provide a home page?

@gwhitney that'd be super!

**Comment by gwhitney** [comment]
Just wanted to provide feedback as to what the holdup is: when I install as described above and go to the Docs page, the sidebar headings are all missing (which I did not realize until I was about to do the PR). I then didn't want to suggest instructions that have led to an impaired installation, but I haven't yet managed to figure out what's wrong. When I get a chance to, I will proceed with a pull request, possibly accompanied by an issue report (but I doubt it, considering frappeframework.com/docs works fine; but unfortunately, I have no way of seeing exactly what's installed on that site/how it's configured).

**Comment by netchampfaris** [comment]
@gwhitney You should not install `frappe_theme` app, just installing `frappe_docs` should be enough.

**Comment by gwhitney** [comment]
Ah, indeed, if I create a new site and only install frappe_docs, the sidebar seems fine. OK, I will shortly submit a PR with an updated readme.
