### ISSUE TITLE
"Frappe Framework - Portal Pages" showing blank content

### ISSUE THREAD

**Issue by JohnVeness** [frappe/frappe_docs#7]
Page https://frappeframework.com/docs/user/en/portal-pages is showing up with mostly blank content, even though it shows a ToC. Checked in Firefox and Chromium.

![image](https://user-images.githubusercontent.com/2512915/85621529-56a3a380-b65d-11ea-8a83-0942b3443d6e.png)

**Comment by TurkerTunali** [comment]
This problem still valid.

**Comment by amenat** [comment]
This is fixed as of now and the issue can be closed.
