### ISSUE TITLE
MariaDB ppas no longer required on ubuntu 20.04

### ISSUE THREAD

**Issue by ankush** [frappe/frappe_docs#97]
https://frappeframework.com/docs/user/en/installation#debian-ubuntu suggests adding mariadb PPA, which are not required on 20.04 as it's already in default repos and also cause conflict.

**Comment by ankush** [comment]
@NagariaHussain

**Comment by NagariaHussain** [comment]
Yes, it causes conflicts when we add the PPA. It works fine without it. Should I update the doc, maybe with a note for Ubuntu 20.04? Or is it the case with all Ubuntu versions?
